name: Daily Player Update

on:
  schedule:
    # 05:00 UTC is 12:00 AM EST
    - cron: '0 5 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial: gives the action permission to push to your repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nba_api pandas

      - name: Run daily player script
        run: python backend/config.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Notice we add the backend/ prefix here too
          git add backend/history.json backend/daily_player.json 
          git commit -m "Update daily player for $(date +'%Y-%m-%d')" || exit 0
          git push